### ISSUE TITLE
Our automated security checks have determined that this request cannot be processed error

### ISSUE THREAD

**Issue by will-bulluck** [adlcmdl/block_definitions#1]
I have a site/clkient trying to use this plugin but the registration renders an error, what they experience is "
I have tried to register but it will not accept it. I complete the form and click register and receive the message: "Our automated security checks have determined that this request cannot be processed."

I have also tried to send a message through Contact Us and it does the same thing when I click submit. The same "Our automated security checks have determined that this request cannot be processed." message."

Any advice is helpful here
Will

**Comment by timmartinez** [comment]
Sounds like their site has some kind of security software that may be keyed on IP address? I tried signing up for a new account and had no issues. Perhaps the client can try from a different location?
